spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/imooc-demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123
  session:
    store-type: none
security:
  basic:
    enabled: true
server:
  port: 8080
#geforce:
#  security:
#    browser:
#      loginPage: /demo-signIn.html
#      loginType: REDIRECT
